### ISSUE TITLE
Remove battle stats (outside of HP) from Pokedex page

### ISSUE THREAD

**Issue by Pengogo** [tigt/ptv#7]
Skills cover the same information. If a GM needs to quick build, this may be a bad idea though

**Comment by tigt** [comment]
> 17:30 \<Tigt> https://github.com/tigt/ptv/issues/7
> 17:30 \<Tigt> how do you feel about this one now
> 17:31 \<Penguingod> Hm, there's more than enough room for them
> 17:31 \<Penguingod> They might as well stay
